### ISSUE TITLE
.sql for german page tree

### ISSUE THREAD

**Issue by siwa-pparzer** [TYPO3-Documentation/site-introduction#1]
Is there a .sql for the german translations also available?

**Comment by DavidBruchmann** [comment]
@siwa-pparzer if this is still relevant, can you elaborate what you mean exactly?
Usually the database tables and fields are the same for every language, so I never understand which difference you expect for German.

**Comment by siwa-pparzer** [comment]
Phew - I can't remember.
Isn't relevant any more.
Can be closed.

**Comment by DavidBruchmann** [comment]
Thank anyway ;-)
