### ISSUE TITLE
Support ddev.site domain names

### ISSUE THREAD

**Issue by ohader** [TYPO3-Documentation/site-introduction#13]
Current setup only supports legacy *.ddev.local domain names and should be adjusted in `env.dist`

* TYPO3_TRUSTED_HOST_PATTERN
* SITE_INTRODUCTION_BASE

**Comment by ohader** [comment]
see PR #14

**Comment by DavidBruchmann** [comment]
@ohader seeing the README I get the impression that this issue is not relevant anymore.  
Would be great if you could confirmm that.
Thanks!

**Comment by DavidBruchmann** [comment]
`ddev.site` names are supported currently by default and I think this is no issue anymore.
