### ISSUE TITLE
./var is readonly on Linux

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Documentation/site-introduction#18]
https://github.com/benjaminkott/site-introduction/blob/24a3aabc619674db86fc13819f3697766bcb41f5/.ddev/docker-compose.tempfs.yaml#L1-L9

With that, `./var` is mounted as root on Linux (with default docker install) and is not writable by the webserver.

The symptom is a blank output and a log entry about the non-writable `./var` directory.

AFAIK this was an early ddev optimization which is not needed anymore due to better cross-platform support for fast filesystem access.

IMHO that file could just be removed.

**Comment by DavidBruchmann** [comment]
Do you mean the whole file `docker-compose.tempfs.yaml` should be removed?

**Comment by DavidBruchmann** [comment]
I tried it and it works like expected, so I close this issue.  
Thanks for reporting!
