### ISSUE TITLE
update composer.json of branch v12-0 when ...

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3-Documentation/site-introduction#34]
- ... bootstrap-package for TYPO3 v12 is released
- ... TYPO3 v12 LTS is released (April 25, 2023)

**Comment by garvinhicking** [comment]
Maybe check my PR here, this could be related: https://github.com/TYPO3-Documentation/site-introduction/pull/37

**Comment by linawolf** [comment]
We started with a fresh version, closing all issues refering the old version
