### ISSUE TITLE
Getting English text on english page instead of German (default in Typo3)

### ISSUE THREAD

**Issue by hilburger** [TYPO3-Documentation/site-introduction#6]
Hi there, 
do you have an idea why I am getting English text although being located in Germany using a German browser? 
I enter the English (language id is 1) page version (/en/..) and I get the message (alright until here) but the text is always Englisch instead of German (language id=0). 

Here ist my config - can't spot my mistake: 

`<?php
return [
    'actions' => [
        [
            'referrers' => [
                'google.',
                'bing.',
                'yahoo.',
                't-online.',
                'yandex.',
                'baidu.',
                'links.playground.localhost.de',
            ],
            'events' => [
                'redirect'
            ]
        ],
        [
            'referrers' => [
                '*'
            ],
            'events' => [
                'suggest'
            ]
        ]
    ],
    'globalConfiguration' => [
        // show suggest message or do a redirect only if the user visits home (not for subpages)
        'actionOnHomeOnly' => false,

        // don't redirect to the home-page, try to stay on the same page while changing the language
        'stayOnCurrentPage' => true
    ],
    'noMatchingConfiguration' => [
        'identifierUsage' => 'worldwide_english',
        'matchMinQuantifier' => 15
    ],
    'redirectConfiguration' => [
        // this number means: pid
        // Worldwide, Europe
        1 => [
            // this number means: language parameter
            0 => [
                'identifier' => 'worldwide_german',
                'domain' => [
                    'www.test.com',
                    'staging.test.com',
                    'www.test.local.stage:8888'
                ],
                'browserLanguage' => [
                    'de'
                ],
                'countryBasedOnIp' => [
                    '*'
                ]
            ],
            1 => [
                'identifier' => 'worldwide_english',
                'domain' => [
	                'www.test.com',
	                'staging.test.com',
	                'www.test.local.stage:8888'
                ],
                'browserLanguage' => [
                    '*'
                ],
                'countryBasedOnIp' => [
                    '*'
                ]
            ],
            2 => [
                'identifier' => 'worldwide_spanish',
                'domain' => [
	                'www.test.com',
	                'staging.test.com',
	                'www.test.local.stage:8888'
                ],
                'browserLanguage' => [
                    'es'
                ],
                'countryBasedOnIp' => [
                    '*'
                ]
            ],
        ],
    ],
    'quantifier' => [
        'browserLanguage' => [
            'totalMatch' => 7,
            'wildCardMatch' => 3
        ],
        'countryBasedOnIp' => [
            'totalMatch' => 13,
            'wildCardMatch' => 5
        ],
        'actions' => [
            'referrers' => [
                'totalMatch' => 7,
                'wildCardMatch' => 3,
            ]
        ]
    ]
];`

**Comment by DavidBruchmann** [comment]
Hi,
thanks for your (quite old) request.  
This repository is about improving the documentation, so your personal issue is regrettable posted on a wrong page.  
For support about this or other issues please refer to these pages:  

- https://docs.typo3.org/
- https://typo3.org/community/meet
